services:
  resource-db:
    image: postgres:16
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_pass
    ports:
      - "5433:5432"

  song-db:
    image: postgres:16
    container_name: song-db
    environment:
      POSTGRES_DB: song_db
      POSTGRES_USER: song_user
      POSTGRES_PASSWORD: song_pass
    ports:
      - "5434:5432"
