spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5434/song_db
    username: song_user
    password: song_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
