spring:
  application:
    name: resource-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:resource_user}
    password: ${SPRING_DATASOURCE_PASSWORD:resource_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8081}
song:
  service:
    url: ${SONG_SERVICE_URL:http://localhost:8082}
    path: ${SONG_SERVICE_PATH:/songs}
